apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-service-api
  labels:
    app: resources-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resources-service
  template:
    metadata:
      labels:
        app: resources-service
    spec:
      containers:
        - name: resources-service-api
          image: 224983445169.dkr.ecr.eu-north-1.amazonaws.com/resources-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: DB_HOST
              value: "rings-quest-4.ck4o8yyu369l.eu-north-1.rds.amazonaws.com"
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "ADD_YOUR_PASSWORD_HERE"
            - name: DB_NAME
              value: "rings_quest"
            - name: GAME_NAME
              value: "rings-quest"
