apiVersion: v1
kind: Service
metadata:
  name: resources-service-svc
spec:
  selector:
    app: resources-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: LoadBalancer
